apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-bluegreen
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/egangithub1502/gitops-nginx-bluegreen'
    targetRevision: main
    path: overlays/green     # <- switch to overlays/green when switching color
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

